import { useState } from "react";
import { useParams, Link } from "react-router-dom";
import { useDocumentTitle } from "@/hooks/useDocumentTitle";
import { MOCK_SUPPLIERS, getGradeLabel, getGrade } from "@/lib/supplierData";
import { GradeBadge } from "@/components/GradeBadge";
import { TrendIndicator } from "@/components/TrendIndicator";
import {
  ArrowLeft, Mail, CheckCircle, AlertTriangle, TrendingUp, TrendingDown,
  Send, X, AlertOctagon, ShieldAlert,
} from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import {
  Dialog, DialogContent, DialogHeader, DialogTitle,
} from "@/components/ui/dialog";
import {
  LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Area, AreaChart,
} from "recharts";

const gradeChartColor: Record<string, string> = {
  A: 'hsl(142, 72%, 36%)',
  B: 'hsl(48, 100%, 50%)',
  C: 'hsl(30, 100%, 50%)',
  D: 'hsl(350, 80%, 50%)',
};

const gradeChartColorFill: Record<string, string> = {
  A: 'hsl(142, 72%, 36%, 0.2)',
  B: 'hsl(48, 100%, 50%, 0.2)',
  C: 'hsl(30, 100%, 50%, 0.2)',
  D: 'hsl(350, 80%, 50%, 0.2)',
};

function getMetricStatus(key: string, value: number): { icon: React.ReactNode; label: string; color: string } {
  if (key === 'otd') {
    if (value >= 95) return { icon: <CheckCircle className="w-4 h-4" />, label: `▲ ${(value - 90).toFixed(1)}%`, color: 'text-success' };
    if (value >= 85) return { icon: <TrendingUp className="w-4 h-4" />, label: 'Acceptable', color: 'text-warning' };
    return { icon: <TrendingDown className="w-4 h-4" />, label: 'Below Target', color: 'text-destructive' };
  }
  if (key === 'fillRate') {
    if (value >= 95) return { icon: <CheckCircle className="w-4 h-4" />, label: 'Stable', color: 'text-success' };
    if (value >= 85) return { icon: <TrendingUp className="w-4 h-4" />, label: 'Acceptable', color: 'text-warning' };
    return { icon: <AlertTriangle className="w-4 h-4" />, label: 'Low', color: 'text-destructive' };
  }
  if (key === 'rejectRate') {
    if (value <= 1) return { icon: <CheckCircle className="w-4 h-4" />, label: 'Good', color: 'text-success' };
    if (value <= 3) return { icon: <TrendingUp className="w-4 h-4" />, label: 'Monitor', color: 'text-warning' };
    return { icon: <AlertTriangle className="w-4 h-4" />, label: 'Critical Fail', color: 'text-destructive' };
  }
  return { icon: null, label: '', color: '' };
}

function getRecommendations(supplier: typeof MOCK_SUPPLIERS[0]): string[] {
  const recs: string[] = [];
  if (supplier.rejectRate > 3) recs.push("Audit supplier production quality processes.");
  if (supplier.otd < 80) recs.push("Investigate delivery delays and renegotiate contract terms.");
  if (supplier.fillRate < 90) recs.push("Review supplier capacity and consider backup vendor.");
  if (supplier.trend === 'Degrading') recs.push("Schedule performance review meeting with supplier.");
  if (supplier.grade === 'D') recs.push("Initiate transition to secondary supplier.");
  if (supplier.trend === 'Erratic') recs.push("Adjust procurement schedule to buffer variability.");
  if (recs.length === 0) recs.push("Continue monitoring. No immediate action required.");
  return recs;
}

function buildEmailSubject(supplier: typeof MOCK_SUPPLIERS[0]): string {
  if (supplier.grade === 'D')
    return `🚨 CRITICAL: Supplier Performance Alert — ${supplier.name} [Grade D]`;
  return `⚠️ WARNING: Supplier Needs Intervention — ${supplier.name} [Grade C]`;
}

function buildEmailBody(supplier: typeof MOCK_SUPPLIERS[0]): string {
  const recs = getRecommendations(supplier);
  const urgency = supplier.grade === 'D' ? 'CRITICAL RISK' : 'INTERVENTION REQUIRED';
  return `Dear Procurement Team,

This is an automated performance alert generated by SupplyLens.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SUPPLIER PERFORMANCE ALERT — ${urgency}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Supplier:        ${supplier.name}
Supplier ID:     ${supplier.id}
Category:        ${supplier.category}
Overall Grade:   ${supplier.grade} (${getGradeLabel(supplier.grade)})
Composite Score: ${supplier.compositeScore}

PERFORMANCE METRICS
───────────────────
• On-Time Delivery:    ${supplier.otd}%
• Fill Rate:           ${supplier.fillRate}%
• Quality Rejection:   ${supplier.rejectRate}%
• 30-Day Trend:        ${supplier.trend}

RECOMMENDED ACTIONS
───────────────────
${recs.map((r, i) => `${i + 1}. ${r}`).join('\n')}

Please review this supplier's performance and take appropriate action at the earliest.

— SupplyLens Automated Alert System`;
}

// ─── Email Modal ──────────────────────────────────────────────────────────────
function EmailModal({
  open,
  onClose,
  supplier,
  onSent,
  onFailed,
}: {
  open: boolean;
  onClose: () => void;
  supplier: typeof MOCK_SUPPLIERS[0];
  onSent: () => void;
  onFailed: () => void;
}) {
  const [to, setTo] = useState("procurement-team@company.com");
  const [subject, setSubject] = useState(buildEmailSubject(supplier));
  const [body, setBody] = useState(buildEmailBody(supplier));
  const [sending, setSending] = useState(false);

  const isD = supplier.grade === 'D';

  const handleSend = async () => {
    setSending(true);
    try {
      const res = await fetch(import.meta.env.VITE_FORMSPREE_ENDPOINT, {
        method: "POST",
        headers: { "Content-Type": "application/json", Accept: "application/json" },
        body: JSON.stringify({
          email: to,
          _subject: subject,
          message: body,
          supplier_name: supplier.name,
          supplier_grade: supplier.grade,
        }),
      });
      if (!res.ok) throw new Error(`Formspree error: ${res.status}`);
      onClose();
      onSent();
    } catch (err) {
      console.error("Formspree error:", err);
      onClose();
      onFailed();
    } finally {
      setSending(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-2xl p-0 overflow-hidden gap-0">
        {/* Header stripe */}
        <div className={`px-6 py-4 flex items-center gap-3 ${isD ? 'bg-destructive' : 'bg-orange-500'}`}>
          <div className="w-9 h-9 rounded-full bg-white/20 flex items-center justify-center flex-shrink-0">
            {isD
              ? <AlertOctagon className="w-5 h-5 text-white" />
              : <ShieldAlert className="w-5 h-5 text-white" />}
          </div>
          <div className="flex-1">
            <DialogTitle className="text-white font-semibold text-base leading-none mb-0.5">
              {isD ? 'Critical Risk Alert' : 'Performance Warning Alert'}
            </DialogTitle>
            <p className="text-white/75 text-xs">
              Notify procurement team about <span className="font-semibold text-white">{supplier.name}</span>
            </p>
          </div>
          <button
            onClick={onClose}
            className="w-7 h-7 rounded-full bg-white/20 hover:bg-white/30 flex items-center justify-center transition-colors"
          >
            <X className="w-4 h-4 text-white" />
          </button>
        </div>

        {/* Grade badge strip */}
        <div className={`px-6 py-2.5 flex items-center gap-2 text-xs font-medium ${isD ? 'bg-red-50 border-b border-red-100' : 'bg-orange-50 border-b border-orange-100'}`}>
          <span className={`px-2 py-0.5 rounded font-bold text-white text-xs ${isD ? 'bg-destructive' : 'bg-orange-500'}`}>
            Grade {supplier.grade}
          </span>
          <span className={isD ? 'text-red-600' : 'text-orange-600'}>
            {getGradeLabel(supplier.grade)} — Score: {supplier.compositeScore} · OTD: {supplier.otd}% · Fill Rate: {supplier.fillRate}% · Rejection: {supplier.rejectRate}%
          </span>
        </div>

        {/* Form */}
        <div className="px-6 py-5 space-y-4">
          {/* To */}
          <div>
            <label className="block text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-1.5">To</label>
            <input
              value={to}
              onChange={(e) => setTo(e.target.value)}
              className="w-full h-9 px-3 text-sm border border-border rounded-md bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-primary/30"
            />
          </div>

          {/* Subject */}
          <div>
            <label className="block text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-1.5">Subject</label>
            <input
              value={subject}
              onChange={(e) => setSubject(e.target.value)}
              className="w-full h-9 px-3 text-sm border border-border rounded-md bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-primary/30"
            />
          </div>

          {/* Body */}
          <div>
            <label className="block text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-1.5">Message</label>
            <textarea
              value={body}
              onChange={(e) => setBody(e.target.value)}
              rows={12}
              className="w-full px-3 py-2.5 text-xs font-mono border border-border rounded-md bg-background text-foreground resize-none focus:outline-none focus:ring-2 focus:ring-primary/30 leading-relaxed"
            />
          </div>
        </div>

        {/* Footer */}
        <div className="px-6 py-4 bg-muted/30 border-t border-border flex items-center justify-between">
          <p className="text-xs text-muted-foreground">
            Sent via <span className="font-semibold text-foreground">SupplyLens</span> Alert System
          </p>
          <div className="flex items-center gap-2">
            <button
              onClick={onClose}
              className="h-9 px-4 text-sm font-medium text-muted-foreground hover:text-foreground border border-border rounded-md hover:bg-background transition-colors"
            >
              Cancel
            </button>
            <button
              onClick={handleSend}
              disabled={sending}
              className={`h-9 px-5 text-sm font-semibold text-white rounded-md inline-flex items-center gap-2 transition-all disabled:opacity-70 ${
                isD
                  ? 'bg-destructive hover:bg-destructive/90'
                  : 'bg-orange-500 hover:bg-orange-600'
              }`}
            >
              {sending ? (
                <>
                  <svg className="animate-spin w-4 h-4" viewBox="0 0 24 24" fill="none">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8z" />
                  </svg>
                  Sending…
                </>
              ) : (
                <>
                  <Send className="w-4 h-4" />
                  Send Alert Email
                </>
              )}
            </button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}

// ─── Page ─────────────────────────────────────────────────────────────────────
export default function SupplierScorecard() {
  const { id } = useParams<{ id: string }>();
  const supplier = MOCK_SUPPLIERS.find((s) => s.id === id);
  const { toast } = useToast();
  const [emailOpen, setEmailOpen] = useState(false);
  useDocumentTitle(supplier ? `${supplier.name} Scorecard` : "Scorecard");

  if (!supplier) {
    return (
      <div className="p-8">
        <p className="text-muted-foreground">Supplier not found.</p>
        <Link to="/suppliers" className="text-primary text-sm hover:underline mt-2 inline-block">Back to suppliers</Link>
      </div>
    );
  }

  const chartData = [...supplier.weeklyScores].reverse();
  const recommendations = getRecommendations(supplier);
  const chartColor = gradeChartColor[supplier.grade] || gradeChartColor.B;
  const chartFill = gradeChartColorFill[supplier.grade] || gradeChartColorFill.B;
  const showSendMail = supplier.grade === 'D' || supplier.grade === 'C';
  const isD = supplier.grade === 'D';

  const handleSent = () => {
    toast({
      title: "✅ Alert Email Sent",
      description: `Performance alert for ${supplier.name} (Grade ${supplier.grade}) was sent to the procurement team.`,
    });
  };

  const handleFailed = () => {
    toast({
      title: "❌ Email Failed to Send",
      description: "Please check your EmailJS credentials in the .env file and try again.",
      variant: "destructive",
    });
  };

  const otdStatus = getMetricStatus('otd', supplier.otd);
  const fillStatus = getMetricStatus('fillRate', supplier.fillRate);
  const rejectStatus = getMetricStatus('rejectRate', supplier.rejectRate);

  return (
    <div className="p-8 max-w-6xl">

      {/* Alert banner for C/D */}
      {showSendMail && (
        <div className={`mb-5 rounded-xl px-5 py-4 flex items-center gap-4 ${
          isD
            ? 'bg-red-50 border border-red-200'
            : 'bg-orange-50 border border-orange-200'
        }`}>
          <div className={`w-10 h-10 rounded-full flex items-center justify-center flex-shrink-0 ${isD ? 'bg-destructive' : 'bg-orange-500'}`}>
            {isD
              ? <AlertOctagon className="w-5 h-5 text-white" />
              : <ShieldAlert className="w-5 h-5 text-white" />}
          </div>
          <div className="flex-1 min-w-0">
            <p className={`font-semibold text-sm ${isD ? 'text-red-700' : 'text-orange-700'}`}>
              {isD ? 'Critical Risk — Immediate Action Required' : 'Performance Intervention Needed'}
            </p>
            <p className={`text-xs mt-0.5 ${isD ? 'text-red-500' : 'text-orange-500'}`}>
              {supplier.name} scored {supplier.compositeScore} (Grade {supplier.grade}). Notify the procurement team immediately.
            </p>
          </div>
          <button
            onClick={() => setEmailOpen(true)}
            className={`relative inline-flex items-center gap-2 px-5 py-2.5 text-sm font-semibold text-white rounded-lg flex-shrink-0 transition-all ${
              isD
                ? 'bg-destructive hover:bg-destructive/90 shadow-lg shadow-red-200'
                : 'bg-orange-500 hover:bg-orange-600 shadow-lg shadow-orange-200'
            }`}
          >
            {/* Pulse ring for Grade D */}
            {isD && (
              <span className="absolute -inset-0.5 rounded-lg animate-ping opacity-30 bg-destructive" />
            )}
            <Mail className="w-4 h-4" />
            Send Alert Email
          </button>
        </div>
      )}

      {/* Top bar */}
      <div className="flex items-center justify-between mb-6">
        <Link to="/suppliers" className="inline-flex items-center gap-2 px-4 py-2 bg-primary text-primary-foreground text-sm font-medium rounded hover:opacity-90 transition-opacity">
          <ArrowLeft className="w-4 h-4" /> Back to Overview
        </Link>
      </div>

      {/* Header Card */}
      <div className="bg-sidebar text-sidebar-foreground rounded-lg p-6 mb-6">
        <div className="flex items-center gap-5">
          <div className="flex flex-col items-center">
            <GradeBadge grade={supplier.grade} size="lg" />
            <span className="text-xs mt-1 text-sidebar-foreground/70">{getGradeLabel(supplier.grade)}</span>
          </div>
          <div className="flex-1">
            <h1 className="text-2xl font-bold">{supplier.name}</h1>
            <div className="flex items-center gap-3 mt-1 text-sm text-sidebar-foreground/70 font-mono">
              <span>-{supplier.id.replace('S', '')}</span>
              <span>Supplier: {supplier.category}</span>
            </div>
          </div>
          <div className="text-right space-y-1 text-sm">
            <div className="text-sidebar-foreground/70">Supplier ID: <span className="font-mono text-sidebar-foreground">{supplier.id}</span></div>
            <div className="text-sidebar-foreground/70">Category: <span className="text-sidebar-foreground">{supplier.category}</span></div>
            <div className="text-sidebar-foreground/70">Overall Grade:
              <span className={`ml-2 inline-flex items-center gap-1 px-3 py-1 rounded text-sm font-bold ${
                supplier.grade === 'A' ? 'bg-success text-success-foreground' :
                supplier.grade === 'B' ? 'bg-primary text-primary-foreground' :
                supplier.grade === 'C' ? 'bg-warning text-warning-foreground' :
                'bg-destructive text-destructive-foreground'
              }`}>
                {supplier.grade} ({getGradeLabel(supplier.grade)})
              </span>
            </div>
          </div>
        </div>
      </div>

      {/* Metrics + Chart */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">
        <div className="border border-border rounded-lg p-6 bg-card space-y-0">
          <div className="flex items-center justify-between border-b border-border py-4">
            <span className="font-semibold text-foreground">On-Time Delivery</span>
            <div className="flex items-center gap-3">
              <span className={`${otdStatus.color}`}>{otdStatus.icon}</span>
              <span className="font-mono font-bold text-xl text-foreground">{supplier.otd}%</span>
              <span className={`text-sm font-medium ${otdStatus.color}`}>{otdStatus.label}</span>
            </div>
          </div>
          <div className="flex items-center justify-between border-b border-border py-4">
            <span className="font-semibold text-foreground">Fill Rate</span>
            <div className="flex items-center gap-3">
              <span className={`${fillStatus.color}`}>{fillStatus.icon}</span>
              <span className="font-mono font-bold text-xl text-foreground">{supplier.fillRate}%</span>
              <span className={`text-sm font-medium ${fillStatus.color}`}>{fillStatus.label}</span>
            </div>
          </div>
          <div className="flex items-center justify-between border-b border-border py-4">
            <span className="font-semibold text-foreground">Quality Rejection</span>
            <div className="flex items-center gap-3">
              <span className={`${rejectStatus.color}`}>{rejectStatus.icon}</span>
              <span className="font-mono font-bold text-xl text-foreground">{supplier.rejectRate}%</span>
              <span className={`text-sm font-medium ${rejectStatus.color}`}>{rejectStatus.label}</span>
            </div>
          </div>
          <div className="flex items-center justify-between pt-4">
            <span className="font-semibold text-foreground">Overall Composite Score</span>
            <div className="flex items-center gap-2">
              <span className={`font-mono font-bold text-2xl ${
                supplier.grade === 'D' ? 'text-destructive' :
                supplier.grade === 'C' ? 'text-warning' :
                supplier.grade === 'B' ? 'text-primary' : 'text-success'
              }`}>
                {supplier.compositeScore}({supplier.grade})
              </span>
              <span className={`text-sm ${
                supplier.grade === 'D' ? 'text-destructive' :
                supplier.grade === 'C' ? 'text-warning' : 'text-muted-foreground'
              }`}>{getGradeLabel(supplier.grade)}</span>
            </div>
          </div>
        </div>

        <div className="border border-border rounded-lg p-6 bg-card">
          <h3 className="text-sm font-semibold text-foreground mb-4">Composite Score Trend</h3>
          <ResponsiveContainer width="100%" height={220}>
            <AreaChart data={chartData}>
              <defs>
                <linearGradient id="scoreGradient" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor={chartColor} stopOpacity={0.3} />
                  <stop offset="95%" stopColor={chartColor} stopOpacity={0.05} />
                </linearGradient>
              </defs>
              <CartesianGrid strokeDasharray="3 3" stroke="hsl(210, 14%, 89%)" />
              <XAxis dataKey="week" tick={{ fontSize: 11, fontFamily: "'IBM Plex Mono'" }} />
              <YAxis domain={[50, 100]} tick={{ fontSize: 11, fontFamily: "'IBM Plex Mono'" }} />
              <Tooltip contentStyle={{ background: "#ffffff", border: "1px solid #bfdbfe", color: "#1e3a8a", fontFamily: "'IBM Plex Mono'", fontSize: 12, borderRadius: 8, boxShadow: "0 4px 16px rgba(37,99,235,0.10)" }} />
              <Area type="monotone" dataKey="composite" stroke={chartColor} strokeWidth={2.5} fill="url(#scoreGradient)" dot={{ r: 5, fill: chartColor, stroke: '#fff', strokeWidth: 2 }} name="Score" />
            </AreaChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* Weekly Breakdown Table */}
      <div className="border border-border rounded-lg overflow-hidden mb-6">
        <table className="w-full text-sm">
          <thead>
            <tr className="bg-card border-b border-border">
              {['Metric', ...chartData.map(d => d.week)].map((h) => (
                <th key={h} className="text-left px-5 py-3 font-medium text-muted-foreground text-xs uppercase tracking-wider">{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {['otd', 'fillRate', 'rejectRate', 'composite'].map((key) => {
              const labels: Record<string, string> = {
                otd: 'On-Time Delivery (OTD %)',
                fillRate: 'Fill Rate (FR %)',
                rejectRate: 'Quality Rejection (QR %)',
                composite: 'Composite Score',
              };
              const isComposite = key === 'composite';
              return (
                <tr key={key} className={`border-b border-border ${isComposite ? 'bg-muted/30 font-semibold' : ''}`}>
                  <td className="px-5 py-3 font-medium text-foreground">{labels[key]}</td>
                  {chartData.map((d, i) => {
                    const val = d[key as keyof typeof d];
                    const numVal = typeof val === 'number' ? val : 0;
                    let textColor = 'text-foreground';
                    if (isComposite) {
                      const g = getGrade(numVal);
                      if (g === 'D') textColor = 'text-destructive font-bold';
                      else if (g === 'C') textColor = 'text-warning font-bold';
                      else if (g === 'B') textColor = 'text-primary font-bold';
                      else textColor = 'text-success font-bold';
                    }
                    return (
                      <td key={i} className={`px-5 py-3 font-mono ${textColor}`}>
                        {isComposite ? `${val} (${getGrade(numVal)})` : `${val}%`}
                      </td>
                    );
                  })}
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* Grade Legend */}
      <div className="border border-border rounded-lg p-5 mb-6 bg-card">
        <div className="grid grid-cols-1 sm:grid-cols-4 gap-3">
          {[
            { grade: 'A', range: '95–100', label: 'Strategic Partner' },
            { grade: 'B', range: '85–94', label: 'Reliable' },
            { grade: 'C', range: '70–84', label: 'Needs Intervention' },
            { grade: 'D', range: '< 70', label: 'Critical Risk / Replace' },
          ].map(({ grade: g, range, label }) => (
            <div key={g} className="flex items-center gap-2 text-sm">
              <GradeBadge grade={g} size="sm" />
              <span className="text-muted-foreground">{g}: {range} ({label})</span>
            </div>
          ))}
        </div>
      </div>

      {/* Recommendations */}
      <div className="border border-border rounded-lg p-6 bg-card">
        <h3 className="font-semibold text-foreground mb-4">System Recommendations</h3>
        <ul className="space-y-2">
          {recommendations.map((r, i) => (
            <li key={i} className="flex items-start gap-2 text-sm text-muted-foreground">
              <span className="text-primary font-mono font-bold">{String(i + 1).padStart(2, '0')}</span>
              {r}
            </li>
          ))}
        </ul>
      </div>

      {/* Email Modal */}
      {showSendMail && (
        <EmailModal
          open={emailOpen}
          onClose={() => setEmailOpen(false)}
          supplier={supplier}
          onSent={handleSent}
          onFailed={handleFailed}
        />
      )}
    </div>
  );
}
